---
- hosts: linux
  remote_user: ansible
  become: yes
  become_method: sudo

  tasks:

  - name: Actualizar paquetes RedHat
    dnf:
      name: "*"
      state: latest
      update_only: yes
    when: ansible_os_family == "RedHat"
    notify: Reiniciar servidor

  - name: Actualizar paquetes en Debian
    apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"
    notify: Reiniciar servidor

  handlers:

  - name: Reiniciar servidor
    reboot:
